POST http://localhost/api/some_view?filter=myfilter&rows=1000 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###

GET http://localhost/api/some_view?filter=myfilter&format=json HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}